name: 'dwh_dbt'
version: '1.0.0'
profile: 'dwh_dbt'

# File path configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories removed by dbt clean
clean-targets:
  - "target"
  - "dbt_packages"


on-run-end: "{{ log_dbt_run() }}"

# Materialisation strategy per layer
models:
  dwh_dbt:
    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: ephemeral

    marts:
      +materialized: table
      +schema: marts

query-comment:
  comment: "This was run by dbt version {{ dbt_version }}"
  append: true


