{#
    Macro: log_dbt_run

    Purpose:
    Writes a single audit record to DWH.AUDIT.DBT_AUDIT every time this macro
    runs, capturing metadata about the dbt invocation (who ran it, what command,
    which target/profile, and when).

    This is typically called from an on-run-start or on-run-end hook in
    dbt_project.yml so it fires automatically on every dbt invocation, e.g:

        on-run-start:
          - "{{ log_dbt_run() }}"

    How it works:
    dbt exposes certain values as Jinja context variables during a run
    (invocation_id, run_started_at, target, dbt_version, etc). This macro
    pulls those values, builds a plain SQL insert statement as a string using
    a `set` block, then executes it with run_query(). Nothing is returned or
    selected, it's a side-effect-only macro used purely for logging.
#}
{% macro log_dbt_run() %}

    {# 
        Build the insert statement as a string.
        Using a `set` block (instead of writing raw SQL directly) lets us
        assemble the query with Jinja variables interpolated in, then pass
        the whole thing to run_query() as one statement.
    #}
    {% set query %}
        insert into DWH.AUDIT.DBT_AUDIT (
            invocation_id,      -- unique ID for this dbt run, auto-generated by dbt
            run_started_at,     -- timestamp when the run began
            dbt_command,        -- the actual command that was run, e.g. "dbt run -s my_model"
            target_profile,     -- the profile name from profiles.yml
            target_name,        -- the target name within that profile, e.g. "dev" or "prod"
            target_user,        -- the warehouse user dbt connected as
            dbt_version         -- version of dbt-core used for this run
        )
        values (
            '{{ invocation_id }}',
            '{{ run_started_at }}',
            '{{ invocation_args_dict["invocation_command"] }}',
            '{{ target.profile_name }}',
            '{{ target.name }}',
            '{{ target.user }}',
            '{{ dbt_version }}'
        );

        commit;
    {% endset %}

    {# 
        run_query() actually sends the SQL to the warehouse and executes it.
        Just building the `query` string above doesn't run anything on its own,
        this is the line that fires it off.
    #}
    {% do run_query(query) %}

{% endmacro %}